/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultManagerSol from "./VaultManager.sol";
export type { vaultManagerSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { VaultStorage } from "./VaultManager.sol/VaultStorage";
export { VaultStorage__factory } from "./factories/VaultManager.sol/VaultStorage__factory";
